BING-25 creates user model
palianskas/bingey pull request #16
Opened 2021-03-18 15:59 UTC by vytautel

Creates user model for MongoDB

2021-03-18 16:04 UTC, palianskas requested changes

2021-03-18 16:04 UTC, palianskas commented on app/bingey-api/models/Users.js
> +const UsersSchema = new Schema({
We should add timestamping to this schema

2021-03-18 16:04 UTC, palianskas commented on app/bingey-api/models/Users.js
> +    watchlistLink: String,
The schema should follow the specified db model

2021-03-18 16:04 UTC, palianskas commented on app/bingey-api/models/Users.js
> +const Users = model('Users', UsersSchema);
The model name should be singular, as it will be pluralized when establishing a connection with the collection

2021-03-18 16:07 UTC, MatasRut requested changes
I created a preliminary db structure file, you can find it in #important discord chat so you should follow those guidelines. Also watchlistLink should be called watchlistId, should be of type Schema.Types.ObjectId and reference the Watchlist schema. You can pass an object instead of the property type like so: { type: Schema.Types.ObjectId, ref: 'Watchlist', required: true }

2021-03-18 18:28 UTC, palianskas requested changes

2021-03-18 18:28 UTC, palianskas commented on app/bingey-api/models/user.js
> +    _id:{
User should have autogenerated IDs, the _Title_ had manually added ones cause we will use the ones from IMDb

2021-03-18 18:28 UTC, palianskas commented on app/bingey-api/models/user.js
> +                ref: 'Titles',
Mongoose has backward-compatibility breaking quirk with pluralization
```suggestion
                ref: 'Title',
```

2021-03-18 18:28 UTC, palianskas commented on app/bingey-api/models/user.js
> +    _id: false,
This shouldn't be added as autogenerated IDs should be used

2021-03-18 18:28 UTC, palianskas commented on app/bingey-api/models/user.js
> +			imgUrl: {
This has some strange indentation haha

2021-03-18 18:28 UTC, palianskas commented on app/bingey-api/models/user.js
> +            },
I think keeping  such field declarations ( _fieldName: type_ ) shorter would be better
```suggestion
            name: String,
```

2021-03-19 13:54 UTC, palianskas requested changes
The indentation is all over the place, does the Prettier not solve it for some reason?
Also, it's not necessary right now as we don't have any actual authentication, but the _password_ field could have a `select: false` option so as to not return it in queries

2021-03-19 18:58 UTC, palianskas approved these changes

2021-03-21 11:39 UTC, merged