Feature/bing 61 design search dropdown
palianskas/bingey pull request #36
Opened 2021-04-30 16:54 UTC by palianskas

Added dropdown to appbar-search to display results (mocked at the moment). On dropdown item click a _title-dialog_  is opened with the data from the dropdown item's title

2021-05-01 15:38 UTC, MatasRut reviewed
CRLF line ending errors appear on every file changed. Reformat files and make sure git is not converting line endings

2021-05-01 16:09 UTC, MatasRut requested changes
Search dropdown items should have a hover effect and the mouse cursor should change to the clicking hand. Right now they do not look clickable.

2021-05-01 16:44 UTC, palianskas commented
> CRLF line ending errors appear on every file changed. Reformat files and make sure git is not converting line endings

Seems like a false flag. Marking as resolved

> Search dropdown items should have a hover effect and the mouse cursor should change to the clicking hand. Right now they do not look clickable.

Moved dropdown's `handleClose` to a different callback, fixed in latest commit

2021-05-02 08:33 UTC, palianskas commented on app/bingey-ui/src/components/Watchlist/TitleDialog/titleDialogStyle.scss
> +.title {
Add overflow ellipsis to long title names

2021-05-02 09:35 UTC, MatasRut approved these changes

2021-05-02 10:12 UTC, merged