Feature/64 redesign title card
palianskas/bingey pull request #44
Opened 2021-05-13 10:07 UTC by palianskas

2021-05-13 10:07 UTC, palianskas commented on app/bingey-api/models/watchlist.js
> +        genres: [String],
Watchlist's reduced titles didn't have a genre field

2021-05-13 10:08 UTC, palianskas commented on app/bingey-ui/src/components/WatchlistsControler/WatchlistPicker/WatchlistPicker.scss
> +.center {
Watchlist picker was using this class from title-card stylesheet that was removed

2021-05-15 09:29 UTC, MatasRut requested changes
Looks good but the line endings again are CRLF, other than that I approve

2021-05-16 13:36 UTC, MatasRut approved these changes

2021-05-16 13:36 UTC, merged